In [62]:
import pandas as pd
import numpy as np


In [63]:
raw_data=pd.read_csv("/content/Absenteeism_dataset.csv")


In [64]:
df=raw_data.copy()


In [65]:
pd.options.display.max_columns=None
pd.options.display.max_rows=None

In [66]:
display(df)

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
5     3                  23  10/07/2015                     179   
6    10                  22  17/07/2015                     361   
7    20                  23  24/07/2015                     260   
8    14                  19  06/07/2015                     155   
9     1                  22  13/07/2015                     235   
10   20                   1  20/07/2015                     260   
11   20                   1  14/07/2015                     260   
12   20                  11  15/07/2015                     260   
13    3                  11  15/07/2015                     179   
14    3                  23  15/07/2015                     179   
15   24                  14  17/07/2015                     246   
16    3                  23  17/07/2015                     179   
17    3                  21  27/07/2015                     179   
18    6                  11  30/07/2015                     189   
19   33                  23  05/08/2015                     248   
20   18                  10  12/08/2015                     330   
21    3                  11  03/08/2015                     179   
22   10                  13  10/08/2015                     361   
23   20                  28  14/08/2015                     260   
24   11                  18  17/08/2015                     289   
25   10                  25  24/08/2015                     361   
26   11                  23  04/08/2015                     289   
27   30                  28  12/08/2015                     157   
28   11                  18  19/08/2015                     289   
29    3                  23  28/08/2015                     179   
30    3                  18  17/08/2015                     179   
31    2                  18  27/08/2015                     235   
32    1                  23  27/08/2015                     235   
33    2                  18  17/08/2015                     235   
34    3                  23  17/08/2015                     179   
35   10                  23  17/08/2015                     361   
36   11                  24  04/08/2015                     289   
37   19                  11  20/08/2015                     291   
38    2                  28  21/08/2015                     235   
39   20                  23  28/08/2015                     260   
40   27                  23  01/09/2015                     184   
41   34                  23  07/09/2015                     118   
42    3                  23  01/09/2015                     179   
43    5                  19  08/09/2015                     235   
44   14                  23  09/09/2015                     155   
45   34                  23  13/09/2015                     118   
46    3                  23  14/09/2015                     179   
47   15                  23  24/09/2015                     291   
48   20                  22  04/09/2015                     260   
49   15                  14  14/09/2015                     291   
50   20                   0  21/09/2015                     260   
51   29                   0  28/09/2015                     225   
52   28                  23  08/09/2015                     225   
53   34                  23  15/09/2015                     118   
54   11                   0  22/09/2015                     289   
55   36                   0  29/09/2015                     118   
56   28                  18  16/09/2015                     225   
57    3                  23  23/09/2015                     179   
58   13                   0  30/09/2015             

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [68]:
df=df.drop(['ID'],axis=1)

In [69]:
df['Reason for Absence'].min()

0

In [70]:
df['Reason for Absence'].max()

28

In [71]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [72]:
reson_cols=pd.get_dummies(df['Reason for Absence'])


In [ ]:
reson_cols['check']=reson_cols.sum(axis=1)
reson_cols

In [74]:
reson_cols['check'].sum(axis=0)

700

In [75]:
reson_cols['check'].unique()

array([1])

In [ ]:
reson_cols=reson_cols.drop(['check'],axis=1)
reson_cols

In [77]:
reson_cols=pd.get_dummies(df['Reason for Absence'],drop_first=True)

In [ ]:
reson_cols

In [79]:
reason_1=reson_cols.iloc[:,1:14].max(axis=1)
reason_2=reson_cols.iloc[:,15:17].max(axis=1)
reason_3=reson_cols.iloc[:,18:21].max(axis=1)
reason_4=reson_cols.iloc[:,22:].max(axis=1)

In [ ]:
df=pd.concat([df,reason_1,reason_2,reason_3,reason_4],axis=1)
df

In [ ]:
df.columns.values

In [82]:
columns_names=['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours', 'reason_1', 'reason_2', 'reason_3', 'reason_4']

In [83]:
df.columns=columns_names

In [84]:
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  reason_1  reason_2  reason_3  reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         0  
3                          4         1         0         0         0  
4                          2         0         0         0         0

In [85]:
df_copy=df.copy()
df_copy.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  reason_1  reason_2  reason_3  reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         0  
3                          4         1         0         0         0  
4                          2         0         0         0         0

In [86]:
type(df_copy['Date'])

pandas.core.series.Series

In [87]:
df_copy['Date']=pd.to_datetime(df_copy['Date'],format='%d/%m/%Y')

In [88]:
df_copy['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
5     2015-07-10
6     2015-07-17
7     2015-07-24
8     2015-07-06
9     2015-07-13
10    2015-07-20
11    2015-07-14
12    2015-07-15
13    2015-07-15
14    2015-07-15
15    2015-07-17
16    2015-07-17
17    2015-07-27
18    2015-07-30
19    2015-08-05
20    2015-08-12
21    2015-08-03
22    2015-08-10
23    2015-08-14
24    2015-08-17
25    2015-08-24
26    2015-08-04
27    2015-08-12
28    2015-08-19
29    2015-08-28
30    2015-08-17
31    2015-08-27
32    2015-08-27
33    2015-08-17
34    2015-08-17
35    2015-08-17
36    2015-08-04
37    2015-08-20
38    2015-08-21
39    2015-08-28
40    2015-09-01
41    2015-09-07
42    2015-09-01
43    2015-09-08
44    2015-09-09
45    2015-09-13
46    2015-09-14
47    2015-09-24
48    2015-09-04
49    2015-09-14
50    2015-09-21
51    2015-09-28
52    2015-09-08
53    2015-09-15
54    2015-09-22
55    2015-09-29
56    2015-09-16
57    2015-09-23
58    2015-09-

In [89]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Reason for Absence         700 non-null    int64         
 1   Date                       700 non-null    datetime64[ns]
 2   Transportation Expense     700 non-null    int64         
 3   Distance to Work           700 non-null    int64         
 4   Age                        700 non-null    int64         
 5   Daily Work Load Average    700 non-null    float64       
 6   Body Mass Index            700 non-null    int64         
 7   Education                  700 non-null    int64         
 8   Children                   700 non-null    int64         
 9   Pets                       700 non-null    int64         
 10  Absenteeism Time in Hours  700 non-null    int64         
 11  reason_1                   700 non-null    uint8         
 12  reason_2

# Now we apply Machine leaning algorithn on our preprocessed data

In [90]:
data_pre=pd.read_csv('/content/Absenteeism_preprocessing_dataset.csv')

In [91]:
data_pre.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [92]:
#create targets
data_pre['Absenteeism Time in Hours'].median()

3.0

In [93]:
targets=np.where(data_pre['Absenteeism Time in Hours'] >
                 data_pre['Absenteeism Time in Hours'].median(),1,0)

In [94]:
data_pre['Excessive Absenteeism']=targets
data_pre.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [95]:
#we are adding break points
data_process=data_pre.copy()
data_process.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [96]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [97]:
data_with_target=data_process.drop(['Absenteeism Time in Hours'],axis=1)

In [98]:
data_with_target is data_process

False

In [99]:
data_with_target.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [100]:
#select the inputs for regression
data_with_target.shape

(700, 15)

In [101]:
unscale_inputs=data_with_target.iloc[:,0:14] #we use also these iloc[:,:14] or iloc[:,:-1]


In [102]:
#standarized the data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [103]:
scaler.fit(unscale_inputs)

StandardScaler()

In [104]:
scaled_inputs=scaler.transform(unscale_inputs)

In [105]:
scaled_inputs.shape

(700, 14)

In [106]:
#split the dataset into train and test
from sklearn.model_selection import train_test_split

In [107]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8)

In [108]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [109]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


In [110]:
#load linear model
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [112]:
#train the model
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression()

In [113]:
reg.score(x_train,y_train)

0.7714285714285715

In [115]:
#check the accuracy
out=reg.predict(x_train)
out

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,

In [117]:
np.sum(out == y_train)

432

In [118]:
out.shape[0]

560

In [119]:
np.sum(out == y_train)/out.shape[0]

0.7714285714285715

In [121]:
#finding intercept and coefficients
reg.intercept_

array([-0.27020137])

In [122]:
reg.coef_

array([[ 2.11234128,  0.375007  ,  1.49163228,  1.32007513,  0.01810141,
        -0.2030411 ,  0.65787862, -0.12700534, -0.27642866, -0.0530042 ,
         0.30589266, -0.11228452,  0.33327956, -0.33307517]])

In [124]:
features_name=unscale_inputs.columns.values

In [125]:
summary_table=pd.DataFrame(columns=['features name'],data=features_name)
summary_table['Coefficients']=np.transpose(reg.coef_)
summary_table

features name  Coefficients
0                  Reason_1      2.112341
1                  Reason_2      0.375007
2                  Reason_3      1.491632
3                  Reason_4      1.320075
4               Month Value      0.018101
5           Day of the Week     -0.203041
6    Transportation Expense      0.657879
7          Distance to Work     -0.127005
8                       Age     -0.276429
9   Daily Work Load Average     -0.053004
10          Body Mass Index      0.305893
11                Education     -0.112285
12                 Children      0.333280
13                      Pet     -0.333075

In [129]:
summary_table.index=summary_table.index + 1
summary_table.loc[0]=['intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

features name  Coefficients
0                 intercept     -0.270201
1                 intercept     -0.270201
4                  Reason_1      2.112341
5                  Reason_2      0.375007
6                  Reason_3      1.491632
7                  Reason_4      1.320075
8               Month Value      0.018101
9           Day of the Week     -0.203041
10   Transportation Expense      0.657879
11         Distance to Work     -0.127005
12                      Age     -0.276429
13  Daily Work Load Average     -0.053004
14          Body Mass Index      0.305893
15                Education     -0.112285
16                 Children      0.333280
17                      Pet     -0.333075

In [132]:
#interpreting the coefficient
summary_table['Odds_ratio']=np.exp(summary_table.Coefficients)
summary_table.sort_values(['Odds_ratio'],ascending=False)
summary_table

features name  Coefficients  Odds_ratio
0                 intercept     -0.270201    0.763226
1                 intercept     -0.270201    0.763226
4                  Reason_1      2.112341    8.267575
5                  Reason_2      0.375007    1.455002
6                  Reason_3      1.491632    4.444344
7                  Reason_4      1.320075    3.743703
8               Month Value      0.018101    1.018266
9           Day of the Week     -0.203041    0.816245
10   Transportation Expense      0.657879    1.930692
11         Distance to Work     -0.127005    0.880729
12                      Age     -0.276429    0.758488
13  Daily Work Load Average     -0.053004    0.948376
14          Body Mass Index      0.305893    1.357837
15                Education     -0.112285    0.893790
16                 Children      0.333280    1.395537
17                      Pet     -0.333075    0.716716

In [133]:
#test the model
reg.score(x_test,y_test)

0.7214285714285714

In [134]:
predicted=reg.predict_proba(x_test)
predicted

array([[0.09015033, 0.90984967],
       [0.54458757, 0.45541243],
       [0.28791732, 0.71208268],
       [0.51316003, 0.48683997],
       [0.25999996, 0.74000004],
       [0.46573448, 0.53426552],
       [0.85253298, 0.14746702],
       [0.06794168, 0.93205832],
       [0.04095835, 0.95904165],
       [0.18880454, 0.81119546],
       [0.51362874, 0.48637126],
       [0.56059202, 0.43940798],
       [0.89156875, 0.10843125],
       [0.12413497, 0.87586503],
       [0.64271712, 0.35728288],
       [0.98113938, 0.01886062],
       [0.75681378, 0.24318622],
       [0.40043582, 0.59956418],
       [0.74151525, 0.25848475],
       [0.84890388, 0.15109612],
       [0.46522418, 0.53477582],
       [0.70074977, 0.29925023],
       [0.9015641 , 0.0984359 ],
       [0.79220729, 0.20779271],
       [0.85007541, 0.14992459],
       [0.82193051, 0.17806949],
       [0.7336042 , 0.2663958 ],
       [0.87248343, 0.12751657],
       [0.68583428, 0.31416572],
       [0.0677057 , 0.9322943 ],
       [0.

In [135]:
predicted.shape


(140, 2)

In [136]:
predicted[:,1]

array([0.90984967, 0.45541243, 0.71208268, 0.48683997, 0.74000004,
       0.53426552, 0.14746702, 0.93205832, 0.95904165, 0.81119546,
       0.48637126, 0.43940798, 0.10843125, 0.87586503, 0.35728288,
       0.01886062, 0.24318622, 0.59956418, 0.25848475, 0.15109612,
       0.53477582, 0.29925023, 0.0984359 , 0.20779271, 0.14992459,
       0.17806949, 0.2663958 , 0.12751657, 0.31416572, 0.9322943 ,
       0.62583121, 0.19709371, 0.52096927, 0.8633249 , 0.25329675,
       0.41782654, 0.22926653, 0.73973559, 0.89908753, 0.18862723,
       0.61206199, 0.77694945, 0.20209965, 0.56817203, 0.26515393,
       0.91149813, 0.9418975 , 0.49347659, 0.10982621, 0.35658424,
       0.54052411, 0.28586074, 0.63061329, 0.75806059, 0.30804574,
       0.30882864, 0.75626853, 0.1343488 , 0.56135542, 0.19327046,
       0.50756381, 0.25124951, 0.21495611, 0.51225712, 0.13472217,
       0.30887728, 0.32326216, 0.14160002, 0.53508071, 0.03308918,
       0.10761546, 0.63227481, 0.17592042, 0.91213793, 0.31478

In [137]:
#save the model
import pickle


In [138]:
with open('model','wb') as file:
  pickle.dump(reg,file)
  